# Generated by Django 3.1.7 on 2021-03-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210327_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
