# Generated by Django 3.1.7 on 2021-03-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210328_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
